:bug: Echo "command not found" message to stderr

diff --git a/.config/zsh/functions/_command_not_found_handler b/.config/zsh/functions/_command_not_found_handler
--- a/.config/zsh/functions/_command_not_found_handler
+++ b/.config/zsh/functions/_command_not_found_handler
@@ -17,6 +17,6 @@ elif (( $+commands[${app_bundled}] )); then
   exec "${app_bundled}" "$@"
 else
   # emulate original zsh behavior
-  echo "$SHELL:t: command not found: ${missing}"
+  echo "$SHELL:t: command not found: ${missing}" >&2
   exit 127
 fi
